# The version is to help determine which version this config is. Please don't modify this value.
configuration-version: 2

# Print additional information in the console. Useful for figuring out errors and issues.
debug: false
# Ignored packets get removed from the debug log.
# Can be an integer for packet ID or name of packet.
ignored-packets:
    - "HEARTBEAT"
    - "SERVER_DATA"

# This value should match the same port defined in the SimpleSkungee configuration on the Proxy.
port: 8000

# The address to bind to.
bind-address: "127.0.0.1"

# If Skungee should parse a word as a Skungee server. There is regex checking to not conflict.
# Example: loop all players on proxy server hub:
skungee-server-parsing: false

# Settings relating to the protocol.
protocol:
    # The packet buffer size in bytes.
    # Default size is the UDP standard 1024
    #
    # If the protocol is sending larger amounts of data (You have a large amount of players, and/or servers)
    # or you're recieving an EOFException. You may want to or be instructed to increase this value.
    buffer-size: 1024

# Reciever is what allows the Proxy Skungee to communicate to the Spigot Skungee.
# The Proxy Skungee can send other events and features from other Spigot servers or the Proxy iteself.
receiver:
    # If this is disabled, some syntax may not work.
    enabled: true
    # Define the ports to run on.
    ports:
        # Automatic will find any open ports and bind to it.
        # When Automatic is enabled, the Spigot Skungee will tell
        # the Proxy Skungee which port it found.
        automatic: true
        # The range of open ports to scan for.
        automatic-range:
            start: 1000
            end: 30000
        # If automatic is false, you can define the port to bind to.
        port: 2000

global-scripts:
    # The charset to send the scripts to the Spigot Skungee as.
    # See https://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html
    charset: "default"
