
# The version is to help determine which version this config is. Please don't modify this value.
configuration-version = 1

# General configurations.
[configurations]

# Print additional information in the console. Useful for figuring out errors and issues.
debug = false
# Packets to be ignored in the debug. Developers of Skungee may ask you to change these values when reporting an issue.
ignored-packets = [
	"HEARTBEAT",
	"SERVER_DATA"
]

# The address to bind to.
bind-address = "127.0.0.1"
# This value should be copied in every other SimpleSkungee spigot server configuration.
port = 8000
ignored-debug = [
  "HEARTBEAT",
  "SERVER_DATA"
]

# All addresses allowed to connected.
# All registered servers to the proxy are already whitelisted addresses.
# If you have addresses that aren't linked to the proxy you can add them here.
whitelisted-addresses = [
  "127.0.0.1"
]

# Configurations relating to the Japson protocol.
[protocol]

# The packet buffer size in bytes.
# Default size is the UDP standard 1024
#
# If the protocol is sending larger amounts of data (You have a large amount of players, and/or servers)
# or you're recieving an EOFException. You may want to or be instructed to increase this value.
buffer-size = 1024

[network-variables]

# The storage type to use.
# The SkungeeAPI allows for registering custom storage systems.
type = "CSV"

[network-variables.backups]

# If Skungee should backup the variables.
enabled = true
# The interval in minutes to backup the variables at.
interval-minutes = 120
# If a message should be broadcasted to the console stating the variables were backed up.
console-messages = true

[global-scripts]

# The charset to send the scripts to the Spigot Skungee as.
# See https://docs.oracle.com/javase/7/docs/api/java/nio/charset/Charset.html
charset = "default"
