# The version is to help determine which version this config is. Please don't modify this value.
configuration-version: 1

# Print additional information in the console. Useful for figuring out errors and issues.
debug: true

# This value should be copied in every other SimpleSkungee spigot server configuration.
port: 8000

# The address to bind to.
bind-address: "localhost"

# Settings relating to the protocol.
protocol:
    # The packet buffer size in bytes.
    # Default size is the UDP standard 1024
    #
    # If the protocol is sending larger amounts of data (You have a large amount of players, and/or servers)
    # or you're recieving an EOFException. You may want to or be instructed to increase this value.
    buffer-size: 1024